name: Test and deploy

on: push

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      #   with:
      #     persist-credentials: false

      # - name: Set up Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version-file: .nvmrc

      - name: test
        run: |
          if [[ -z "${{ secrets.NPM_TOKEN }}" ]]; then
            echo "NPM_TOKEN is not set"
            exit 1
          else
            echo "NPM_TOKEN is set"
          fi
      # - name: Install dependencies
      #   run: npm ci

      # - name: Run tests
      #   run: npm test

      # - name: Run build
      #   run: npm run build

      # - name: Publish
      #   if: github.ref == 'refs/heads/master'
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
